openapi: 3.0.0

info:
  description: "API with webhooks to process events from Active Campaign"
  version: "1.0.0"
  title: "Neso API"
paths:
  /message/{key}:
    post:
      summary: "Send message with specific key"
      description: "The key represent what message to send. The messages content are store in AWS SSM"
      operationId: "sendMessage"
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/ActiveCampaignWebhookRequest"
      parameters:
      - in: "path"
        name: "key"
        description: "Message key"
        required: true
        schema:
            type: string
      responses:
        "200":
          description: "Success"
components:
    schemas:
        ActiveCampaignWebhookResponse:
            type: "object"
            properties:
                statusCode:
                    type: "integer"
                body:   
                    type: "string"
        ActiveCampaignWebhookRequest:
            type: "object"
            properties:
                contact:
                    type: "object"
                    properties:
                        first_name:
                            type: "string"
                        last_name:
                            type: "string"
                        phone:
                            type: "string"
                        id:
                            type: "string"
                        fields:
                            type: "object"
                            properties:
                                link_do_boleto:
                                    type: "string"