AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless application to process phones and send whatsapp messages

Parameters:
  UCHATURL:
    Type: String
    Description: uChat URl do post the message
    Default: https://v1.utalk.chat/send
  UCHATTOKEN:
    Type: String
    Description: uChat Token
    Default: 123abc

Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 10
    Layers:
      - !Ref CommLayer
      - 'arn:aws:lambda:sa-east-1:580247275435:layer:LambdaInsightsExtension:12'


Resources:
  WaMessageParserDLQ:
    Type: AWS::SQS::Queue
  WaMessageParserQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt WaMessageParserDLQ.Arn
        maxReceiveCount: 2
  WaMessageSenderDLQ:
    Type: AWS::SQS::Queue
  WaMessageSenderQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt WaMessageSenderDLQ.Arn
        maxReceiveCount: 2
  CommLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: comm-layer
      CompatibleRuntimes:
      - nodejs12.x
      Description: Common layer for WaSender and Webhooks
      ContentUri: ./layer
  ActiveCampaignWebhook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/active-campaign-webhook/
      Description: Endpoint to process whatsapp message events and send to queue
      Events:
        PostMessage:
          Type: Api
          Properties:
            Path: /message/{key}
            Method: POST
      Environment:
        Variables:
          QUEUE: !Ref WaMessageParserQueue
      Policies:
        - 'arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy'
        - Statement:
            - Sid: SSMGetParameterPolicy
              Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: '*'
        - Statement:
            - Sid: SQSQueuePolicy
              Effect: Allow
              Action:
                - SQS:SendMessage
              Resource:
                - !GetAtt WaMessageParserQueue.Arn
                - !GetAtt WaMessageParserDLQ.Arn
  WaParser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/parser/
      Description: Function to parser WhatsApp messages and send to sender funtion
      Events:
        messageQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt WaMessageParserQueue.Arn
            BatchSize: 10
      Environment:
        Variables:
          DLQ: !Ref WaMessageParserDLQ
          SENDER_QUEUE: !Ref WaMessageSenderQueue
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt WaMessageParserDLQ.Arn
      Policies:
        - 'arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy'
        - Statement:
            - Sid: SQSQueuePolicy
              Effect: Allow
              Action:
                - SQS:SendMessage
              Resource:
                - !GetAtt WaMessageParserDLQ.Arn
                - !GetAtt WaMessageSenderQueue.Arn
  WaSender:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 15
      CodeUri: bin/sender/
      Description: Function to send whatsapp message
      Events:
        messageQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt WaMessageSenderQueue.Arn
            BatchSize: 10
      Environment:
        Variables:
          UCHAT_URL: !Ref UCHATURL
          UCHAT_TOKEN: !Ref UCHATTOKEN
          DLQ: !Ref WaMessageSenderDLQ
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt WaMessageSenderDLQ.Arn
      Policies:
        - 'arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy'