AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless application to process phones and send whatsapp messages

Parameters:
  UCHATURL:
    Type: String
    Description: uChat URl do post the message
    Default: localhost:8080
  UCHATTOKEN:
    Type: String
    Description: uChat Token
    Default: 123abc

Resources:
  wpWebhook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/webhook/
      Handler: index.handler
      Runtime: nodejs12.x
      Description: Endpoint to process events and send to queue
      MemorySize: 128
      Timeout: 10
      Events:
        PostMessage:
          Type: Api
          Properties:
            Path: /message/{key}
            Method: POST
  wpSender:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/sender/
      Handler: index.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          UCHAT_URL: !Ref UCHATURL
          UCHAT_TOKEN: !Ref UCHATTOKEN
      Events:
        phonesQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt phonesQueue.Arn
            BatchSize: 10
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt phonesDLQ.Arn
  phonesDLQ:
    Type: AWS::SQS::Queue
  phonesQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt phonesDLQ.Arn
        maxReceiveCount: 2

