AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless application to process phones and send whatsapp messages

Parameters:
  UCHATURL:
    Type: String
    Description: uChat URl do post the message
    Default: https://v1.utalk.chat/send
  UCHATTOKEN:
    Type: String
    Description: uChat Token
    Default: 123abc

Resources:
  waMessageDLQ:
    Type: AWS::SQS::Queue
  waMessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt waMessageDLQ.Arn
        maxReceiveCount: 2
  FallbackMessage:
    Type: AWS::SSM::Parameter
    Properties:
      Name: fallback
      Type: String
      Value: Hello World!
      Description: Fallback message
  activeCampaignWebhook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/active-campaign-webhook/
      Handler: index.handler
      Runtime: nodejs12.x
      Description: Endpoint to process whatsapp message events and send to queue
      MemorySize: 128
      Timeout: 10
      Events:
        PostMessage:
          Type: Api
          Properties:
            Path: /message/{key}
            Method: POST
      Environment:
        Variables:
          QUEUE: !Ref waMessageQueue
      Policies:
        - Statement:
            - Sid: SSMGetParameterPolicy
              Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: '*'
        - Statement:
            - Sid: SQSQueuePolicy
              Effect: Allow
              Action:
                - SQS:SendMessage
              Resource:
                - !GetAtt waMessageQueue.Arn
                - !GetAtt waMessageDLQ.Arn
  waSender:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/sender/
      Handler: index.handler
      Runtime: nodejs12.x
      Description: Function to send whatsapp message
      MemorySize: 128
      Timeout: 10
      Events:
        messageQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt waMessageQueue.Arn
            BatchSize: 10
      Environment:
        Variables:
          UCHAT_URL: !Ref UCHATURL
          UCHAT_TOKEN: !Ref UCHATTOKEN
          DLQ: !Ref waMessageDLQ
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt waMessageDLQ.Arn