AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless application to process phones and send whatsapp messages

Parameters:
  UCHATURL:
    Type: String
    Description: uChat URl do post the message
    Default: https://v1.utalk.chat/send
  UCHATTOKEN:
    Type: String
    Description: uChat Token
    Default: 123abc

Resources:
  wpMessageDLQ:
    Type: AWS::SQS::Queue
  wpMessageQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt wpMessageDLQ.Arn
        maxReceiveCount: 2
  wpWebhook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/webhook/
      Handler: index.handler
      Runtime: nodejs12.x
      Description: Endpoint to process whatsapp message events and send to queue
      MemorySize: 128
      Timeout: 10
      Events:
        PostMessage:
          Type: Api
          Properties:
            Path: /message/{key}
            Method: POST
      Environment:
        Variables:
          QUEUE: !Ref wpMessageQueue
      Policies:
        - Statement:
            - Sid: SSMGetParameterPolicy
              Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: '*'
        - Statement:
            - Sid: SQSQueuePolicy
              Effect: Allow
              Action:
                - SQS:SendMessage
              Resource:
                - !GetAtt wpMessageQueue.Arn
                - !GetAtt wpMessageDLQ.Arn
  wpSender:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/sender/
      Handler: index.handler
      Runtime: nodejs12.x
      Description: Function to send whatsapp message
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          UCHAT_URL: !Ref UCHATURL
          UCHAT_TOKEN: !Ref UCHATTOKEN
      Events:
        messageQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt wpMessageQueue.Arn
            BatchSize: 10
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt wpMessageDLQ.Arn