name: Deploy DynamoDB to Development
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy DynamoDB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: aws
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_AWS_REGION }}

      - name: Configure variables
        shell: bash
        id: vars
        env:
          REPO: ${{ github.event.repository.name }}
        run: |
          STACK=`echo $REPO | tr "/" "-"`
          STACKID=`echo $STACK-DynamoDB-${{ steps.aws.outputs.aws-account-id }}`
          echo "::set-output name=stack::$STACKID"
          echo "The region is ${{ secrets.AWS_REGION }}"
          echo "The stack id is $STACKID"

      - name: Deploy
        run: |
          aws cloudformation deploy \
          --template-file infrastructure/dynamoDB.json \
          --stack-name ${{ steps.vars.outputs.stack }}