name: Deploy to AWS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy SAM stack to AWS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

#      - run: curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.10
#        name: Install Yarn

#      - run: pip install --upgrade setuptools ; python3 -m pip install boto3
#        name: Install boto3

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate
        run: sam validate

      - name: Configure variables
        shell: bash
        id: vars
        env:
          REPO: ${{ github.event.repository.name }}
          HASH: ${{ github.sha }}
          REF: ${{ github.ref }}
        run: |
          STACK=`echo $REPO | tr "/" "-"`
          echo "::set-output name=stack::$STACK"
          # Output variables to ensure their values are set correctly when ran
          echo "The region is ${{ secrets.AWS_REGION }}"
          echo "The stack is $STACK"

      - name: Build
        run: chmod +x .github/utils/build.sh ; .github/utils/build.sh

#      - run: python3 .github/utils/create-bucket.py ${{ steps.vars.outputs.environment }} ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        name: Create Bucket

      - name: Deploy
        run: |
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name ${{ steps.vars.outputs.stack }} \
            --parameter-overrides 'ParameterKey=UCHATTOKEN,ParameterValue=${{ secrets.UCHAT_TOKEN }}' \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM