name: Deploy to Development
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy SAM stack to AWS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - run: |
          sudo apt-get install python3-setuptools &&
          python3 -m pip install boto3 &&
          curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.10
        name: Install dependencies

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: aws
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.DEV_AWS_REGION }}

      - name: Build
        run: yarn build

      - name: Configure variables
        shell: bash
        id: vars
        env:
          REPO: ${{ github.event.repository.name }}
        run: |
          STACK=`echo $REPO | tr "/" "-"`
          STACKID=`echo $STACK-${{ steps.aws.outputs.aws-account-id }}`
          echo "::set-output name=stack::$STACKID"
          echo "The region is ${{ secrets.AWS_REGION }}"
          echo "The stack id is $STACKID"
      - name: Create Bucket
        run: python3 .github/utils/create-bucket.py \
          ${{ steps.vars.outputs.stack }} \
          ${{ secrets.DEV_AWS_ACCESS_KEY_ID }} \
          ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }} \
          ${{ secrets.DEV_AWS_REGION }}

      - name: Deploy
        run: |
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name ${{ steps.vars.outputs.stack }} \
            --s3-bucket ${{ steps.vars.outputs.stack }} \
            --parameter-overrides 'ParameterKey=UCHATTOKEN,ParameterValue=${{ secrets.UCHAT_TOKEN }}' \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
